name: flutter_application_1
description: "PackAndGo"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.0.0
  shared_preferences: ^2.0.15
  image_picker: ^0.8.4+4 
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/pictures/background.jpg
    - assets/pictures/logo.png
    - assets/pictures/default_avatar.jpg